---
# 模型参数
vocab_size: 5000 # 词汇数目
embedding_dim: 100 # embedding 维度
hidden_size: 200 # 隐藏单元维度
num_layers: 2 # LSTM 层数
dropout: 0.5
bidirectional: false # 是否双向 LSTM
num_labels: 10

# 训练参数
epoch: 10
batch_size: 64
max_seq_len: 1000
print_per_batch: 100